import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/provider";
import { Toaster } from "@/components/ui/sonner";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "NASA-Image",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider session={session}>
					<Providers>
						<main>{children}</main>
						<Toaster richColors />
					</Providers>
				</SessionProvider>
			</body>
		</html>
	);
}
